
package minswp;

/**
 *
 * @author Pooja~Priya
 */
public class MinSwp extends javax.swing.JFrame {

    /**
     * Creates new form MinSwp
     */
    int l=6,w=6,m=10;
    int lft;
    int flg_num=0;
    Stage s;
    AIPlayer ai;
    AIPlayer2 ai2;
    public MinSwp() {
        initComponents();
        lft=l*w;
        min_num_d.setText(m+"");
        //try
        {
            s = new Stage(l,w,m,this);
            statehandler.setVisible(false);
            stagehandler.add(s);
            ai2 = new AIPlayer2(l, w, m,s.bh2);
            ai = new AIPlayer(l, w, m,s.bh2);
        }
        //catch(Exception ex){}
    }
    public MinSwp(Stage sin) {
        initComponents();
        lft=l*w;
        min_num_d.setText(m+"");
        //try
        {
            //s2 = new Stage(l,w,m,this);
            s=sin;
            statehandler.setVisible(false);
            stagehandler.add(s);
            ai2 = new AIPlayer2(l, w, m,s.bh2);
            ai = new AIPlayer(l, w, m,s.bh2);
        }
        //catch(Exception ex){}
    }
 
    public void won()
    {
        //s.setDisable(l,w);
        statehandler.setVisible(true);
        showstate.setText("you won");
        ai.stop();
        ai2.stop();
    }
    public void lost()
    {
        
       // s.setDisable(l,w);
        statehandler.setVisible(true);
        showstate.setText("you Lost"); 
        ai2.stop();
        ai.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        statehandler = new javax.swing.JPanel();
        showstate = new javax.swing.JLabel();
        stagehandler = new javax.swing.JPanel();
        min_num_d = new javax.swing.JLabel();
        flaged_disp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lengthh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        widthh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        minn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ai_b = new javax.swing.JButton();
        aidisp = new javax.swing.JButton();
        ai_b1 = new javax.swing.JButton();
        duplicate_board = new javax.swing.JButton();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Solution");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        statehandler.setBackground(new java.awt.Color(51, 51, 255));
        statehandler.setLayout(new java.awt.GridLayout(1, 1));

        showstate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        showstate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showstate.setText("t");
        statehandler.add(showstate);

        stagehandler.setBackground(new java.awt.Color(204, 255, 204));
        stagehandler.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                stagehandlerComponentRemoved(evt);
            }
        });
        stagehandler.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                stagehandlerAncestorRemoved(evt);
            }
        });
        stagehandler.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                stagehandlerMouseMoved(evt);
            }
        });
        stagehandler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stagehandlerMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stagehandlerMouseReleased(evt);
            }
        });
        stagehandler.setLayout(new java.awt.GridLayout(1, 1));

        min_num_d.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        min_num_d.setForeground(new java.awt.Color(51, 51, 51));
        min_num_d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min_num_d.setText("10");

        flaged_disp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        flaged_disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flaged_disp.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Mines");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Flaged");

        lengthh.setText("10");

        jLabel3.setText("Length");

        widthh.setText("10");

        jLabel4.setText("Width");

        minn.setText("20");

        jLabel5.setText("mines");

        ai_b.setText("AI");
        ai_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ai_bActionPerformed(evt);
            }
        });

        aidisp.setText("table");
        aidisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidispActionPerformed(evt);
            }
        });

        ai_b1.setText("AI 2");
        ai_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ai_b1ActionPerformed(evt);
            }
        });

        duplicate_board.setText("Same");
        duplicate_board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicate_boardActionPerformed(evt);
            }
        });

        start.setText("New");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(statehandler, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lengthh)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(widthh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minn)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(flaged_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(duplicate_board, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(min_num_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(aidisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(stagehandler, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ai_b1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(ai_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(min_num_d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flaged_disp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lengthh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(duplicate_board, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(widthh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aidisp)
                                .addGap(47, 47, 47)
                                .addComponent(ai_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ai_b1))
                            .addComponent(stagehandler, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addComponent(statehandler, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stagehandlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stagehandlerMouseClicked
     
    }//GEN-LAST:event_stagehandlerMouseClicked
    private void stagehandlerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stagehandlerMouseReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_stagehandlerMouseReleased
    private void stagehandlerAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_stagehandlerAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_stagehandlerAncestorRemoved
    private void stagehandlerComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_stagehandlerComponentRemoved
       // TODO add your handling code here:
    }//GEN-LAST:event_stagehandlerComponentRemoved
    private void stagehandlerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stagehandlerMouseMoved

    }//GEN-LAST:event_stagehandlerMouseMoved

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        l=Integer.parseInt(lengthh.getText());
        w=Integer.parseInt(widthh.getText());
        m=Integer.parseInt(minn.getText());
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinSwp().setVisible(true);
            }
        });
         this.dispose();
    }//GEN-LAST:event_startActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     s.discloseMine();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ai_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ai_bActionPerformed
        ai.setRunnable();
        ai.play();
    }//GEN-LAST:event_ai_bActionPerformed

    private void aidispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidispActionPerformed
        ai.showTable(l,w);
    }//GEN-LAST:event_aidispActionPerformed

    private void ai_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ai_b1ActionPerformed
        ai2.setRunnable();
        ai2.play(); 
    }//GEN-LAST:event_ai_b1ActionPerformed

    private void duplicate_boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicate_boardActionPerformed
        //l=Integer.parseInt(lengthh.getText());
        //w=Integer.parseInt(widthh.getText());
        //m=Integer.parseInt(minn.getText());
        s.getCopyMine(l, w);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinSwp(s).setVisible(true);
            }
        });
         this.dispose();
    }//GEN-LAST:event_duplicate_boardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinSwp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinSwp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinSwp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinSwp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinSwp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ai_b;
    private javax.swing.JButton ai_b1;
    private javax.swing.JButton aidisp;
    private javax.swing.JButton duplicate_board;
    public javax.swing.JLabel flaged_disp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lengthh;
    private javax.swing.JLabel min_num_d;
    private javax.swing.JTextField minn;
    private javax.swing.JLabel showstate;
    private javax.swing.JPanel stagehandler;
    private javax.swing.JButton start;
    private javax.swing.JPanel statehandler;
    private javax.swing.JTextField widthh;
    // End of variables declaration//GEN-END:variables
}
